data_path: "data/positions.fen"
max_game_length: 5
max_move_time: 10000
max_depth: 3

# ignore, only for hydra
defaults:
    - _self_
    - override hydra/hydra_logging: disabled
    - override hydra/job_logging: disabled

hydra:
    output_subdir: null
    run:
        dir: .
