data_path: "./data/fens/positions-small.fen"
model_save_path: "./data/models/"
max_game_length: 5
max_move_time: 10000
max_depth: 3
lr: 0.0001
max_memory: 20
no_change_range: 30

defaults:
    - _self_
    - override hydra/hydra_logging: disabled
    - override hydra/job_logging: disabled

hydra:
    output_subdir: null
    run:
        dir: .
