data_path: "data/positions-small.fen"
max_game_length: 5
max_move_time: 10000
max_depth: 3
lr: 0.0001
max_memory: 20
gamma: 0.5

# ignore, only for hydra
defaults:
    - _self_
    - override hydra/hydra_logging: disabled
    - override hydra/job_logging: disabled

hydra:
    output_subdir: null
    run:
        dir: .
